"""Na tabela mega_sena_model colocado resultados da megasena

Revision ID: 249924621af6
Revises: bfcd0cf0620d
Create Date: 2021-04-15 08:16:22.417498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249924621af6'
down_revision = 'bfcd0cf0620d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('megasena', sa.Column('result_megasena', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('megasena', 'result_megasena')
    # ### end Alembic commands ###
