"""Alterado o nome da tabela para Megasena

Revision ID: bfcd0cf0620d
Revises: 07c2cd1dedca
Create Date: 2021-04-15 01:20:16.161031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcd0cf0620d'
down_revision = '07c2cd1dedca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('megasena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.String(length=100), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('games_played', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='game_users_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_pkey')
    )
    op.drop_table('megasena')
    # ### end Alembic commands ###
